CC = gcc
LIB = -lpthread

all: server client

server: myftpserver.c myftp.c myftp.h
	${CC} -o myftpserver myftpserver.c myftp.c ${LIB}

client: myftpclient.c  myftp.c myftp.h
	${CC} -o myftpclient myftpclient.c myftp.c ${LIB}

clean:
	rm myftpserver
	rm myftpclient	
